# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6922280fbf93c027c33b394d19907074eacfd8caf2922544e2deb8654a6d94978ab8d4f201f1bca278700d8959fea99935100e34029eae9790c602c173652e86

test:
  secret_key_base: 4a240687f679b05b7d24bc243d59792bba26aff08db26a170036c043dba4f6d8f2a663d8a0e41d134b4babbcf7ae63d79cf077af3f948e3cc3c8f35f678f7b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
